module.exports = [
{
	"title":"Noderscast – E06 – [En Vivo] Hablemos de Seniority, con Fernando Larragaña",
	"url":"http://d1xuhndp8unoax.cloudfront.net/EP06.mp3",
	"pubdate":"Wed, 09 Sep 2015 19:34:33 +0000",
	"content":"Episodio 06\nEn vivo desde la DevCon – Chile, con nuestro invitado, Fernando Larragaña @xabadu, Ingeniero Civil Informático, Software y Game Developer, actualmente trabaja en Groupon Chile, conversamos sobre qué significa ser un Senior Developer en la industria del desarrollo de software, y cuales son las características principales que debe tener un Senior developer además de derribar ciertos mitos de la industria.\nPor supuesto, conversamos con Fernando sobre su evolución como desarrollador, como parte de equipo de Groupon, emprendedor y profesor.\nRecuerden! Somos una Fan-arquía, el show lo hacen ustedes!, así que envíennos sus sugerencias, comentarios, ideas al twitter @Noderscast, o al correo noderscast@noders.com.\nNos acompañan como siempre Nicolas @elBuraBure, Felipe @fforres y Luis @lporras16\nShowNotes:\n\n\nThe Role of a Senior Developer: http://mattbriggs.net/blog/2015/06/01/the-role-of-a-senior-developer/\nPodcast hecho en Vivo en la Defconf: https://www.youtube.com/watch?v=GJ3ZyUWsg8U\n\n\nPicks of the day!\n\nJS13K Games : http://js13kgames.com/ – Twitter\nDon’t Make me Think: A common Sense Approach to Web Usability : http://www.amazon.com/Dont-Make-Me-Think-Usability/dp/0321344758\nFeria Friki en Santiago: https://m.facebook.com/feriafriki\nMR. ROBOT : http://www.imdb.com/title/tt4158110/\n\nUn abrazo asíncrono!\nEl equipo de NodersCast\n]]>",
	"sumary":"Episodio 06\nEn vivo desde la DevCon - Chile, con nuestro invitado, Fernando Larragaña @xabadu, Ingeniero Civil Informático, Software y Game Developer, actualmente trabaja en Groupon Chile, conversamos sobre qué significa ser un Senior Developer en la industria del desarrollo de software, y cuales son las características principales que debe tener un Senior developer además de derribar ciertos mitos de la industria.\n\nPor supuesto, conversamos con Fernando sobre su evolución como desarrollador, como parte de equipo de Groupon, emprendedor y profesor.\n\nRecuerden! Somos una Fan-arquía, el show lo hacen ustedes!, así que envíennos sus sugerencias, comentarios, ideas al twitter @Noderscast, o al correo noderscast@noders.com.\n\nNos acompañan como siempre Nicolas @elBuraBure, Felipe @fforres y Luis @lporras16\nShowNotes:\n\n\n\tThe Role of a Senior Developer: http://mattbriggs.net/blog/2015/06/01/the-role-of-a-senior-developer/\n\tPodcast hecho en Vivo en la Defconf: https://www.youtube.com/watch?v=GJ3ZyUWsg8U\n\n\nPicks of the day!\n\n\tJS13K Games : http://js13kgames.com/ - Twitter\n\tDont Make me Think: A common Sense Approach to Web Usability : http://www.amazon.com/Dont-Make-Me-Think-Usability/dp/0321344758\n\tFeria Friki en Santiago: https://m.facebook.com/feriafriki\n\tMR. ROBOT : http://www.imdb.com/title/tt4158110/\n\nUn abrazo asíncrono!\nEl equipo de NodersCast",
	"content_w_tags":"",
	"duration":"00:55:37"
},
{
	"title":"Noderscast – E05 – Data Visualization, Mastering D3 y Axiomzen, con Pablo Navarro",
	"url":"http://d1xuhndp8unoax.cloudfront.net/EP05.mp3",
	"pubdate":"Mon, 24 Aug 2015 23:13:03 +0000",
	"content":"Episodio 05\nNuestro invitado, Pablo Navarro @pnavarrc, Ingeniero matemáticio, Autor del libro “Mastering D3.js”, y actualmente, Front end developer y Data Conductor en Axiomzen,\nEn esta ocasión hablamos con Pablo Navarro, sobre visualización de datos, y D3.js,  (Data Driven Documents) y diversas librerías de visualización, como amcharts y raphael, y servicios de visualización de datos.\nPor supuesto, conversamos sobre la historia de Pablo, como developer, analista de datos, ingeniero matemático y Autor.\nSomos una Fan-arquía, el show lo hacen ustedes!, así que envíennos sus sugerencias, comentarios, ideas al twitter @Noderscast, o al correo noderscast@noders.com.\nEntre otros temas que tratamos se encuentran:\n\nUsar D3.js en otros Contextos.\nEjemplos de uso en D3.js\nD3 y WebGL\nWeb Mobile y Ionic.\nAngular y D3.js\nPerformance mobile, Canvas vs D3.js\n\nNos acompañan como siempre Nicolas @elBuraBure, Felipe @fforres y Luis @lporras16\nShowNotes:\n\n\nMasstering D3.js (http://www.amazon.com/Mastering-D3-js-Visualization-JavaScript-Developers/dp/178328627X)\nImpactOn Hackaton: http://www.impacton.org\nD3.js y Angular (https://www.dashingd3js.com/d3-resources/d3-and-angular)\nD3.js y SVG Mobile (http://coenraets.org/blog/2014/02/interactive-mobile-dashboard-d3-charts/)\nKibana (https://www.elastic.co/webinars/kibana-made-simple)\nGrafana (http://grafana.org)\nEVAL (http://www.w3schools.com/jsref/jsref_eval.asp)\n\n\nPicks of the day!\n\nPathGL (http://pathgl.com/)\nRelay and GraphQL(http://facebook.github.io/react/blog/2015/02/20/introducing-relay-and-graphql.html) (https://facebook.github.io/react/blog/2015/05/01/graphql-introduction.html) (http://facebook.github.io/relay/)\nProgramming isn’t manual labor, but it still sucks (http://mashable.com/2014/04/30/programming-sucks/)\nReactive Manifesto (http://www.reactivemanifesto.org/es)\nStartechconf (http://www.startechconf.com/)\nLeanPub (https://leanpub.com/)\n“Bloquear tiempo sin interrupciones”\n“Si trabajan en algo, y se encuentran con algo que no saben… busquen la explicación de inmediato, para encontrar información en el contexto”\nPostula a AxiomZen (https://careers.axiomzen.co/)\nTheGraphicalWeb (https://www.graphicalweb.org/2015/)\n\nEl equipo de NodersCast\n \n]]>",
	"sumary":"Episodio 05\nNuestro invitado, Pablo Navarro @pnavarrc, Ingeniero matemáticio, Autor del libro Mastering D3.js, y actualmente, Front end developer y Data Conductor en Axiomzen,\nEn esta ocasión hablamos con Pablo Navarro, sobre visualización de datos, y D3.js,  (Data Driven Documents) y diversas librerías de visualización, como amcharts y raphael, y servicios de visualización de datos.\nPor supuesto, conversamos sobre la historia de Pablo, como developer, analista de datos, ingeniero matemático y Autor.\nSomos una Fan-arquía, el show lo hacen ustedes!, así que envíennos sus sugerencias, comentarios, ideas al twitter @Noderscast, o al correo noderscast@noders.com.\nEntre otros temas que tratamos se encuentran:\n\nUsar D3.js en otros Contextos.\nEjemplos de uso en D3.js\nD3 y WebGL\nWeb Mobile y Ionic.\nAngular y D3.js\nPerformance mobile, Canvas vs D3.js\n\nNos acompañan como siempre Nicolas @elBuraBure, Felipe @fforres y Luis @lporras16\nShowNotes:\n\n\nMasstering D3.js (http://www.amazon.com/Mastering-D3-js-Visualization-JavaScript-Developers/dp/178328627X)\nImpactOn Hackaton: http://www.impacton.org\nD3.js y Angular (https://www.dashingd3js.com/d3-resources/d3-and-angular)\nD3.js y SVG Mobile (http://coenraets.org/blog/2014/02/interactive-mobile-dashboard-d3-charts/)\nKibana (https://www.elastic.co/webinars/kibana-made-simple)\nGrafana (http://grafana.org)\nEVAL (http://www.w3schools.com/jsref/jsref_eval.asp)\n\n\nPicks of the day!\n\nPathGL (http://pathgl.com/)\nRelay and GraphQL(http://facebook.github.io/react/blog/2015/02/20/introducing-relay-and-graphql.html) (https://facebook.github.io/react/blog/2015/05/01/graphql-introduction.html) (http://facebook.github.io/relay/)\nProgramming isnt manual labor, but it still sucks (http://mashable.com/2014/04/30/programming-sucks/)\nReactive Manifesto (http://www.reactivemanifesto.org/es)\nStartechconf (http://www.startechconf.com/)\nLeanPub (https://leanpub.com/)\nBloquear tiempo sin interrupciones\nSi trabajan en algo, y se encuentran con algo que no saben... busquen la explicación de inmediato, para encontrar información en el contexto\nPostula a AxiomZen (https://careers.axiomzen.co/)\nTheGraphicalWeb (https://www.graphicalweb.org/2015/)\n\nEl equipo de NodersCast\nandnbsp;\n",
	"content_w_tags":"",
	"duration":"01:16:16"
},
{
	"title":"Noderscast – E04 – Torrent TV con Carlos Guerrero",
	"url":"http://d1xuhndp8unoax.cloudfront.net/EP04.mp3",
	"pubdate":"Mon, 10 Aug 2015 14:04:42 +0000",
	"content":"Episodio 04\nNuestro invitado Carlos Guerrero – @guerrerocarlos, developer, consultor, DevOp e Ingeniero Electrónico, creador de Proxy DNS y TorrentTV.\nEn esta ocasión hablamos sobre la tecnología BitTorrent, y como ha sido utilizada a lo largo del tiempo para compartir información a gran escala, convirtiéndose así en un instrumento tanto del bien como del mal.   Por supuesto hablaremos de  la experiencia que tuvo Carlos como creador de la aplicación TorrentTV, la cual permite reproducir videos contenidos en archivos torrents transmitiendo directamente a un ChromeCast y que además es de código abierto, y se puede encontrar en GitHub.\nEntre otros temas que tratamos se encuentran:\n\nQué es BitTorrent y porqué es importante.\nAlternativas a TorrentTV.\nEmpresas/Productos que utilizan la tecnología BitTorrent legalmente.\nEmpresas/Productos que utilizan la tecnología BitTorrent ilegalmente.\n\nNos acompañan como siempre Nicolas @elBuraBure, Felipe @fforres y Luis @lporras16\nShowNotes:\n\n\nStreams, Peerflix, and node-webkit – http://dailyjs.com/2014/10/31/peerflix/\nImpactOn Hackaton: http://www.impacton.org\nRescue Time https://www.rescuetime.com\nBtApp.js: backbone library that provides easy access to Torque/BitTorrent/uTorrent clients.) https://github.com/bittorrenttorque/btapp\nMDB (modular debugger) and Node.js:  https://www.joyent.com/blog/mdb-and-node-js\nIronNode – Debug Node.js code with Chrome Developer Tools on Linux, Windows and OS X: https://github.com/s-a/iron-node\nFacebook usa Torrent para el deployment: http://arstechnica.com/business/2012/04/exclusive-a-behind-the-scenes-look-at-facebook-release-engineering/\nTwitter – Murder Bittorrent Deploy System: https://vimeo.com/11280885  https://github.com/lg/murder\nStreaming JSON loading for Node and browsers: http://oboejs.com/\nPut.io: http://put.io\nBitTorrent Sync: https://www.getsync.com\n\n\nPicks of the day!\n\nReadme.io:  Beauty Documentation made Easy http://readme.io\nHacker Jobs – Hired.com: https://hired.com\nHacker Jobs – HackerRank: https://www.hackerrank.com\nHacker Jobs – GetonBrd: https://www.getonbrd.cl\nDesarrollador Aprendiz en Santiago Labs: https://www.getonbrd.cl/empleos/programacion/desarrollador-junior-santiagolab\nPomodoro Technique: http://www.tomato.es http://pomodorotechnique.com\nTalk – Redemption from Callback Hell: https://www.youtube.com/watch?v=hf1T_AONQJU\nDoes BitTorrent == piracy? http://www.doesbittorrentequalpiracy.com\nAudible, Audiolibros + Game Of thrones\nRestriccion Vehicular en Santiago de Chile, proyecto de codigo abierto: http://TengoRestriccion.cl\nTalk – Mathias Buus Madsen: Javascript… Torrents… and Mad Science!: https://www.youtube.com/watch?v=BTCsSwCpGP8\n\nEl equipo de NodersCast\n \n \n]]>",
	"sumary":"Episodio 04\nNuestro invitado Carlos Guerrero - @guerrerocarlos, developer, consultor, DevOp e Ingeniero Electrónico, creador de Proxy DNS y TorrentTV.\n\nEn esta ocasión hablamos sobre la tecnología BitTorrent, y como ha sido utilizada a lo largo del tiempo para compartir información a gran escala, convirtiéndose así en un instrumento tanto del bien como del mal.   Por supuesto hablaremos de  la experiencia que tuvo Carlos como creador de la aplicación TorrentTV, la cual permite reproducir videos contenidos en archivos torrents transmitiendo directamente a un ChromeCast y que además es de código abierto, y se puede encontrar en GitHub.\n\nEntre otros temas que tratamos se encuentran:\n\n\tQué es BitTorrent y porqué es importante.\n\tAlternativas a TorrentTV.\n\tEmpresas/Productos que utilizan la tecnología BitTorrent legalmente.\n\tEmpresas/Productos que utilizan la tecnología BitTorrent ilegalmente.\n\nNos acompañan como siempre Nicolas @elBuraBure, Felipe @fforres y Luis @lporras16\nShowNotes:\n\n\n\tStreams, Peerflix, and node-webkit - http://dailyjs.com/2014/10/31/peerflix/\n\tImpactOn Hackaton: http://www.impacton.org\n\tRescue Time https://www.rescuetime.com\n\tBtApp.js: backbone library that provides easy access to Torque/BitTorrent/uTorrent clients.) https://github.com/bittorrenttorque/btapp\n\tMDB (modular debugger) and Node.js:  https://www.joyent.com/blog/mdb-and-node-js\n\tIronNode - Debug Node.js code with Chrome Developer Tools on Linux, Windows and OS X: https://github.com/s-a/iron-node\n\tFacebook usa Torrent para el deployment: http://arstechnica.com/business/2012/04/exclusive-a-behind-the-scenes-look-at-facebook-release-engineering/\n\tTwitter - Murder Bittorrent Deploy System: https://vimeo.com/11280885  https://github.com/lg/murder\n\tStreaming JSON loading for Node and browsers: http://oboejs.com/\n\tPut.io: http://put.io\n\tBitTorrent Sync: https://www.getsync.com\n\n\nPicks of the day!\n\n\tReadme.io:  Beauty Documentation made Easy http://readme.io\n\tHacker Jobs - Hired.com: https://hired.com\n\tHacker Jobs - HackerRank: https://www.hackerrank.com\n\tHacker Jobs - GetonBrd: https://www.getonbrd.cl\n\tDesarrollador Aprendiz en Santiago Labs: https://www.getonbrd.cl/empleos/programacion/desarrollador-junior-santiagolab\n\tPomodoro Technique: http://www.tomato.es http://pomodorotechnique.com\n\tTalk - Redemption from Callback Hell: https://www.youtube.com/watch?v=hf1T_AONQJU\n\tDoes BitTorrent == piracy? http://www.doesbittorrentequalpiracy.com\n\tAudible, Audiolibros + Game Of thrones\n\tRestriccion Vehicular en Santiago de Chile, proyecto de codigo abierto: http://TengoRestriccion.cl\n\tTalk - Mathias Buus Madsen: Javascript... Torrents... and Mad Science!: https://www.youtube.com/watch?v=BTCsSwCpGP8\n\nEl equipo de NodersCast\nandnbsp;\n\nandnbsp;",
	"content_w_tags":"",
	"duration":"01:17:35"
},
{
	"title":"Noderscast – E03 – NodebotsDay Chile, Elk Stack y Seguridad Web –  Live episode",
	"url":"http://d1xuhndp8unoax.cloudfront.net/EP03.mp3",
	"pubdate":"Tue, 28 Jul 2015 21:18:06 +0000",
	"content":"Episodio 03\nEn esta ocasión revelamos  los inconvenientes que tuvimos realizando un podcast, el cual no pudimos publicar, pero que tenemos pensado repetir y lanzar en un futuro episodio.  También conversamos la experiencia en la organización del evento NodeBotsDay en Chile, más un resumen del mismo.\nPor último tocamos varios temas interesantes como la hackaton ImpactOnChile, Logging de aplicaciones en Node.js, ELK Stack (ElasticSearch/Logstash/Kibana), seguridad Web y el proyecto OpenSource que estuvo trabajando Nicolas realizado con React.js y Webpack, Koa.js, el cual estará lanzando en los próximos días.\nNos acompañan como siempre Nicolas @elBuraBure, Felipe @fforres y Luis @lporras16\nShowNotes:\n\n\nNodeBots – http://nodebots.io/\nELK Stack https://www.elastic.co/webinars/introduction-elk-stack\nHackaton ImpactOn Chile\nLibrerías de Logging para Node.js: Bunyan (https://github.com/trentm/node-bunyan), Winston (https://github.com/winstonjs/winston)\nHomakov Rails Hack http://homakov.blogspot.com/2012/03/how-to.html\nURSA – RSA public/private key OpenSSL bindings for Node.js (https://github.com/quartzjer/ursa)\nTalk: Jeremy Stashewsky: Preventing XSS & CSRF (https://www.youtube.com/watch?v=_jubb3g1HVg&)\n\n\nPicks of the day!\n\nTalk: Ryan Florence – Don’t Rewrite, React! – https://www.youtube.com/watch?v=BF58ZJ1ZQxY\nTalk: Simplicity matters, Rich Hickey – https://www.youtube.com/watch?v=rI8tNMsozo0\nAWS Lambda –  http://aws.amazon.com/documentation/lambda/\nRabbitMQ Patterns for Appplications – http://derickbailey.com/email-courses/rabbitmq-patterns-for-applications/\nTalk: Angelina Fabbro: JavaScript Masterclass | JSConfUS 2013 (https://www.youtube.com/watch?v=v0TFmdO4ZP0)\nTalk: Javascript: Understanding the Weird Parts – The First 3.5 Hours (https://www.youtube.com/watch?v=Bv_5Zv5c-Ts)\n\nEl equipo de NodersCast\n \n \n]]>",
	"sumary":"Episodio 03\nEn esta ocasión revelamos  los inconvenientes que tuvimos realizando un podcast, el cual no pudimos publicar, pero que tenemos pensado repetir y lanzar en un futuro episodio.  También conversamos la experiencia en la organización del evento NodeBotsDay en Chile, más un resumen del mismo.\n\nPor último tocamos varios temas interesantes como la hackaton ImpactOnChile, Logging de aplicaciones en Node.js, ELK Stack (ElasticSearch/Logstash/Kibana), seguridad Web y el proyecto OpenSource que estuvo trabajando Nicolas realizado con React.js y Webpack, Koa.js, el cual estará lanzando en los próximos días.\n\nNos acompañan como siempre Nicolas @elBuraBure, Felipe @fforres y Luis @lporras16\nShowNotes:\n\n\n\tNodeBots - http://nodebots.io/\n\tELK Stack https://www.elastic.co/webinars/introduction-elk-stack\n\tHackaton ImpactOn Chile\n\tLibrerías de Logging para Node.js: Bunyan (https://github.com/trentm/node-bunyan), Winston (https://github.com/winstonjs/winston)\n\tHomakov Rails Hack http://homakov.blogspot.com/2012/03/how-to.html\n\tURSA - RSA public/private key OpenSSL bindings for Node.js (https://github.com/quartzjer/ursa)\n\tTalk: Jeremy Stashewsky: Preventing XSS andamp; CSRF (https://www.youtube.com/watch?v=_jubb3g1HVgandamp;)\n\n\nPicks of the day!\n\n\tTalk: Ryan Florence - Dont Rewrite, React! - https://www.youtube.com/watch?v=BF58ZJ1ZQxY\n\tTalk: Simplicity matters, Rich Hickey - https://www.youtube.com/watch?v=rI8tNMsozo0\n\tAWS Lambda -  http://aws.amazon.com/documentation/lambda/\n\tRabbitMQ Patterns for Appplications - http://derickbailey.com/email-courses/rabbitmq-patterns-for-applications/\n\tTalk: Angelina Fabbro: JavaScript Masterclass | JSConfUS 2013 (https://www.youtube.com/watch?v=v0TFmdO4ZP0)\n\tTalk: Javascript: Understanding the Weird Parts - The First 3.5 Hours (https://www.youtube.com/watch?v=Bv_5Zv5c-Ts)\n\nEl equipo de NodersCast\nandnbsp;\n\nandnbsp;",
	"content_w_tags":"",
	"duration":"01:22:05"
},
{
	"title":"NodersCast – E02 – NodeBots, JSConf y más con Julian Duque",
	"url":"http://d1xuhndp8unoax.cloudfront.net/EP02.mp3",
	"pubdate":"Fri, 03 Jul 2015 19:58:18 +0000",
	"content":"Episodio 02\nNuestro invitado Julián Duque @julian_duque, developer y educador apasionado, organizador de Medellin.js y JSConf Colombia, Ingeniero de Software en la compañía NodeSource.\nEn esta ocasión hablamos de la experiencia de Julián como organizador de Medellin.js y la JSConf de Colombia 2015, su participación en las distintas conferencias de Javascript donde ha sido charlista y el movimiento NodeBot, del cual forma parte y ha aportado como colaborador de Johnny Five el framework más destacado para la programación de Robots con Javascript.\nNos acompañan como siempre Nicolas @elBuraBure, Felipe @fforres y Luis @lporras16\nShowNotes:\n\n\nNodeBots – http://nodebots.io/\nJohnny Five – http://johnny-five.io/\nNodeSchool – http://nodeschool.io/es/\nReact Hardware – https://github.com/iamdustan/react-hardware\nConsigue tu vuelo más económico con https://skiplagged.com/\n\n\nPicks of the day!\n\nMaps for the Web made Easy – https://cartodb.com/\nJSConf Colombia – http://jsconf.co/\nAtom el editor del futuro – https://atom.io\nJSVerify testing basado en propiedades – https://jsverify.github.io/\nFirebase, PaaS Bases de datos en tiempo real – https://www.firebase.com/\nSense 8 – https://www.netflix.com/Sense8\nDragon Ball Z: Resurrection ‘F’ – http://www.imdb.com/title/tt3819668/\nNos vemos en el próximo episodio!\n\nEl equipo de NodersCast\n \n \n]]>",
	"sumary":"Episodio 02\nNuestro invitado Julián Duque @julian_duque, developer y educador apasionado, organizador de Medellin.js y JSConf Colombia, Ingeniero de Software en la compañía NodeSource.\n\nEn esta ocasión hablamos de la experiencia de Julián como organizador de Medellin.js y la JSConf de Colombia 2015, su participación en las distintas conferencias de Javascript donde ha sido charlista y el movimiento NodeBot, del cual forma parte y ha aportado como colaborador de Johnny Five el framework más destacado para la programación de Robots con Javascript.\n\nNos acompañan como siempre Nicolas @elBuraBure, Felipe @fforres y Luis @lporras16\nShowNotes:\n\n\n\tNodeBots - http://nodebots.io/\n\tJohnny Five - http://johnny-five.io/\n\tNodeSchool - http://nodeschool.io/es/\n\tReact Hardware - https://github.com/iamdustan/react-hardware\n\tConsigue tu vuelo más económico con https://skiplagged.com/\n\n\nPicks of the day!\n\n\tMaps for the Web made Easy - https://cartodb.com/\n\tJSConf Colombia - http://jsconf.co/\n\tAtom el editor del futuro - https://atom.io\n\tJSVerify testing basado en propiedades - https://jsverify.github.io/\n\tFirebase, PaaS Bases de datos en tiempo real - https://www.firebase.com/\n\tSense 8 - https://www.netflix.com/Sense8\n\tDragon Ball Z: Resurrection F - http://www.imdb.com/title/tt3819668/\n\nNos vemos en el próximo episodio!\n\nEl equipo de NodersCast\nandnbsp;\n\nandnbsp;",
	"content_w_tags":"",
	"duration":"01:07:05"
},
{
	"title":"NodersCast – E01 – Inicios en programación, mantenerse actualizado, y comunidades de devs",
	"url":"http://d1xuhndp8unoax.cloudfront.net/EP01_v1.mp3",
	"pubdate":"Fri, 19 Jun 2015 00:15:07 +0000",
	"content":"Episodio 01\nNuestra invitada Marisol Acuña @MarisolAcuña, emprendedora, developer, fundadora de timepoints, blogger en http://disfrutandoelmundo.com, owner http://soloparafans.cl, y Director de Women Who Code Santiago. @wwcscl\nEn esta ocasión hablamos del rol de las mujeres en tecnología, y la iniciativa Women Who Code, de los inicios de cada uno de los asistentes en el mundo de tecnología y desarrollo, y las metodologías y estrategias para mantenerse actualizado en este cada ves mas cambiante ecosistema.\nNos acompañan como siempre Nicolas @elBuraBure, Felipe @fforres y Luis @lporras16\nShowNotes:\n\n2030: Privacy’s dead, Tom Scott – https://youtu.be/_kBlH-DQsEg\nRework, Jason Fried, http://37signals.com/rework/\nThe Two Pillars of Javascript, Eric Elliott – https://medium.com/javascript-scene/the-two-pillars-of-javascript-ee6f3281e7f3 (edited)\nCodeschool – Javascript.com\nShai Reznik – NG-WAT\nNoders.com\nEggHead.io\n\nPicks of the day!\n\nMadMax – Fury Road\nEric Elliott – http://ericleads.com/\nHashtag700\nThe Flash – La serie\nWomenWhoCodeSantiago\nInkaConf\nJSconf Colombia\nStartechConf\nWorld Tech Makers\n\n \nNos vemos en el próximo episodio!\nEl equipo de NodersCast\n \n \n\n]]>\n\t\tEpisodio 01\nNuestra invitada Marisol Acuña @MarisolAcuña, emprendedora, developer, fundadora de timepoints, blogger en http://disfrutandoelmundo.com, owner http://soloparafans.cl, y Director de Women Who Code Santiago. @wwcscl\n\nEn esta ocasión hablamos del rol de las mujeres en tecnología, y la iniciativa Women Who Code, de los inicios de cada uno de los asistentes en el mundo de tecnología y desarrollo, y las metodologías y estrategias para mantenerse actualizado en este cada ves mas cambiante ecosistema.\n\nNos acompañan como siempre Nicolas @elBuraBure, Felipe @fforres y Luis @lporras16\nShowNotes:\n\n\t2030: Privacys dead, Tom Scott - https://youtu.be/_kBlH-DQsEg\n\tRework, Jason Fried, http://37signals.com/rework/\n\tThe Two Pillars of Javascript, Eric Elliott - https://medium.com/javascript-scene/the-two-pillars-of-javascript-ee6f3281e7f3 (edited)\n\tCodeschool - Javascript.com\n\tShai Reznik - NG-WAT\n\tNoders.com\n\tEggHead.io\n\nPicks of the day!\n\n\tMadMax - Fury Road\n\tEric Elliott - http://ericleads.com/\n\tHashtag700\n\tThe Flash - La serie\n\tWomenWhoCodeSantiago\n\tInkaConf\n\tJSconf Colombia\n\tStartechConf\n\tWorld Tech Makers\n\nandnbsp;\nNos vemos en el próximo episodio!\nEl equipo de NodersCast\nandnbsp;\n\nandnbsp;\n\t\t\n\t\tNo\n\t\tNo\n\t\t1:09:21\n\t\tNodersCast\n\t\n",
	"sumary":"Episodio 01\nNuestra invitada Marisol Acuña @MarisolAcuña, emprendedora, developer, fundadora de timepoints, blogger en http://disfrutandoelmundo.com, owner http://soloparafans.cl, y Director de Women Who Code Santiago. @wwcscl\n\nEn esta ocasión hablamos del rol de las mujeres en tecnología, y la iniciativa Women Who Code, de los inicios de cada uno de los asistentes en el mundo de tecnología y desarrollo, y las metodologías y estrategias para mantenerse actualizado en este cada ves mas cambiante ecosistema.\n\nNos acompañan como siempre Nicolas @elBuraBure, Felipe @fforres y Luis @lporras16\nShowNotes:\n\n\t2030: Privacys dead, Tom Scott - https://youtu.be/_kBlH-DQsEg\n\tRework, Jason Fried, http://37signals.com/rework/\n\tThe Two Pillars of Javascript, Eric Elliott - https://medium.com/javascript-scene/the-two-pillars-of-javascript-ee6f3281e7f3 (edited)\n\tCodeschool - Javascript.com\n\tShai Reznik - NG-WAT\n\tNoders.com\n\tEggHead.io\n\nPicks of the day!\n\n\tMadMax - Fury Road\n\tEric Elliott - http://ericleads.com/\n\tHashtag700\n\tThe Flash - La serie\n\tWomenWhoCodeSantiago\n\tInkaConf\n\tJSconf Colombia\n\tStartechConf\n\tWorld Tech Makers\n\nandnbsp;\nNos vemos en el próximo episodio!\nEl equipo de NodersCast\nandnbsp;\n\nandnbsp;\n",
	"content_w_tags":"",
	"duration":"1:09:21"
}
];